### ISSUE TITLE
not works on cloudflare

### ISSUE THREAD

**Issue by nandish486** [Hex1629/SOCKETPIE_DOSTOOL#10]

**Comment by Hex1629** [comment]
Site and now i need stopped for working anything update

**Comment by nandish486** [comment]
> Site and now i need stopped for working anything update

no worries, i alived it again i added my made bypassers it bypass in 3 sec. but bro

help me by hint or something to ddos sites with ratelimit?

**Comment by Hex1629** [comment]
and that it not for attack cloudflare it was http thing
