### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by HaveNTime122** [Hex1629/SOCKETPIE_DOSTOOL#12]
![Screenshot_2024-09-17_10_47_43](https://github.com/user-attachments/assets/0dc45832-65e3-4a5e-8c10-4002121ee0ad)

even after choosing minimum thread amount, booter etc. have troubles with "too many open files
![Screenshot_2024-09-17_10_50_41](https://github.com/user-attachments/assets/0c94bb72-0c36-4d18-b775-2e573bd4e086)
"

**Comment by Hex1629** [comment]
it normal error case by i not type **try: except:**

**Comment by unnamedman122** [comment]
mate, is there any way to run more threads? i have like 8gb on my vbox machine and it uses only 1.5. also it starts showing error after opening 2000 sockets

**Comment by HaveNTime122** [comment]
![Screenshot_2024-09-17_16_12_21](https://github.com/user-attachments/assets/4401635d-5c00-49f7-8fc1-7d8f5859e2be)
![Screenshot_2024-09-17_16_44_20](https://github.com/user-attachments/assets/5629fa81-93f9-4e4b-b133-a46ce3c0f193)
